# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: "http://tranzexact.github.io"
title: tranzexact
email: tranzexact1@gmail.com
author: Tranzexact
description: > # Let us process your transactions so you can focus on strategy!
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2016 Tranzexact. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url:
  - title: github
    url: https://github.com/tranzexact
  - title: linkedin
    url:
